using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;

var builder = WebApplication.CreateBuilder(args);
const string JwtKey = "AdminPro-portfolio-key-2026-change-this-in-production-very-long";
builder.Services.AddDbContext<AppDb>(o => o.UseSqlite("Data Source=adminpro_portfolio.db"));
builder.Services.AddCors(o => o.AddDefaultPolicy(p => p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(o => o.TokenValidationParameters = new TokenValidationParameters { ValidateIssuer=false, ValidateAudience=false, ValidateLifetime=true, ValidateIssuerSigningKey=true, IssuerSigningKey=new SymmetricSecurityKey(Encoding.UTF8.GetBytes(JwtKey)) });
builder.Services.AddAuthorization(o => o.AddPolicy("AdminOnly", p => p.RequireRole("Admin")));
builder.Services.AddEndpointsApiExplorer(); builder.Services.AddSwaggerGen();
var app = builder.Build();
using (var scope = app.Services.CreateScope()) { var db=scope.ServiceProvider.GetRequiredService<AppDb>(); db.Database.EnsureCreated(); Seed(db); }
app.UseCors(); app.UseAuthentication(); app.UseAuthorization(); app.UseSwagger(); app.UseSwaggerUI();

app.MapGet("/api/health", () => Results.Ok(new { status="ok", service="AdminPro Portfolio API" }));
app.MapPost("/api/auth/login", async (LoginDto x, AppDb db) => {
    var email=x.Email.Trim().ToLowerInvariant(); var u=await db.Users.FirstOrDefaultAsync(a=>a.Email==email);
    if(u is null || !Hashing.Verify(x.Password,u.PasswordHash) || !u.IsActive) return Results.Unauthorized();
    var claims=new[]{new Claim(ClaimTypes.NameIdentifier,u.Id.ToString()),new Claim(ClaimTypes.Name,u.Name),new Claim(ClaimTypes.Role,u.Role),new Claim(ClaimTypes.Email,u.Email)};
    var token=new JwtSecurityToken(claims:claims,expires:DateTime.UtcNow.AddHours(8),signingCredentials:new SigningCredentials(new SymmetricSecurityKey(Encoding.UTF8.GetBytes(JwtKey)),SecurityAlgorithms.HmacSha256));
    db.Logs.Add(new ActivityLog{Action="Login",Details=$"{u.Name} logged in",UserId=u.Id,CreatedAt=DateTime.UtcNow}); await db.SaveChangesAsync();
    return Results.Ok(new { token=new JwtSecurityTokenHandler().WriteToken(token), user=UserDto.From(u) });
});
app.MapGet("/api/me", async (ClaimsPrincipal p, AppDb db) => { var id=UserId(p); var u=await db.Users.FindAsync(id); return u is null?Results.NotFound():Results.Ok(UserDto.From(u)); }).RequireAuthorization();
app.MapPut("/api/me", async (ProfileInput x, ClaimsPrincipal p, AppDb db) => { var id=UserId(p); var u=await db.Users.FindAsync(id); if(u is null)return Results.NotFound(); if(string.IsNullOrWhiteSpace(x.Name))return Results.BadRequest("Name is required."); u.Name=x.Name.Trim(); await db.SaveChangesAsync(); return Results.Ok(UserDto.From(u)); }).RequireAuthorization();
app.MapPut("/api/me/password", async (PasswordChange x, ClaimsPrincipal p, AppDb db) => { var id=UserId(p); var u=await db.Users.FindAsync(id); if(u is null)return Results.NotFound(); if(!Hashing.Verify(x.CurrentPassword,u.PasswordHash))return Results.BadRequest("Current password is incorrect."); u.PasswordHash=Hashing.Hash(x.NewPassword); await db.SaveChangesAsync(); return Results.Ok(new{message="Password changed successfully."}); }).RequireAuthorization();

app.MapGet("/api/dashboard", async (ClaimsPrincipal p, AppDb db) => {
    var isAdmin=p.IsInRole("Admin"); var uid=UserId(p); var taskQ=db.Tasks.AsQueryable(); if(!isAdmin) taskQ=taskQ.Where(t=>t.AssigneeId==uid);
    var total=await taskQ.CountAsync(); var pending=await taskQ.CountAsync(t=>t.Status=="Pending"); var progress=await taskQ.CountAsync(t=>t.Status=="In Progress"); var done=await taskQ.CountAsync(t=>t.Status=="Done"); var overdue=await taskQ.CountAsync(t=>t.DueDate!=null&&t.DueDate<DateTime.UtcNow.Date&&t.Status!="Done");
    return Results.Ok(new{users=isAdmin?await db.Users.CountAsync():1,departments=await db.Departments.CountAsync(),employees=await db.Employees.CountAsync(),tasks=total,pendingTasks=pending,inProgressTasks=progress,completedTasks=done,overdueTasks=overdue});
}).RequireAuthorization();

// Users
app.MapGet("/api/users", async (AppDb db) => Results.Ok(await db.Users.OrderByDescending(x=>x.Id).Select(x=>new UserRow(x.Id,x.Name,x.Email,x.Role,x.IsActive)).ToListAsync())).RequireAuthorization("AdminOnly");
app.MapPost("/api/users", async (UserInput x, ClaimsPrincipal p, AppDb db) => { if(string.IsNullOrWhiteSpace(x.Name)||string.IsNullOrWhiteSpace(x.Email)||string.IsNullOrWhiteSpace(x.Password))return Results.BadRequest("Name, email and password are required."); var email=x.Email.Trim().ToLowerInvariant(); if(await db.Users.AnyAsync(u=>u.Email==email))return Results.Conflict("Email already exists."); var u=new User{Name=x.Name.Trim(),Email=email,PasswordHash=Hashing.Hash(x.Password),Role=x.Role=="Admin"?"Admin":"Employee",IsActive=true}; db.Users.Add(u); await db.SaveChangesAsync(); await Log(db,p,"Created user",u.Name); return Results.Ok(UserDto.From(u)); }).RequireAuthorization("AdminOnly");
app.MapPut("/api/users/{id:int}", async (int id, UserInput x, ClaimsPrincipal p, AppDb db) => { var u=await db.Users.FindAsync(id); if(u is null)return Results.NotFound(); var email=x.Email.Trim().ToLowerInvariant(); if(await db.Users.AnyAsync(a=>a.Id!=id&&a.Email==email))return Results.Conflict("Email already exists."); u.Name=x.Name.Trim();u.Email=email;u.Role=x.Role=="Admin"?"Admin":"Employee";u.IsActive=x.IsActive; if(!string.IsNullOrWhiteSpace(x.Password))u.PasswordHash=Hashing.Hash(x.Password); await db.SaveChangesAsync(); await Log(db,p,"Updated user",u.Name); return Results.Ok(UserDto.From(u)); }).RequireAuthorization("AdminOnly");
app.MapDelete("/api/users/{id:int}", async (int id, ClaimsPrincipal p, AppDb db) => { if(UserId(p)==id)return Results.BadRequest("You cannot delete your own account."); var u=await db.Users.FindAsync(id); if(u is null)return Results.NotFound();db.Users.Remove(u);await db.SaveChangesAsync();await Log(db,p,"Deleted user",u.Name);return Results.NoContent(); }).RequireAuthorization("AdminOnly");

// Departments
app.MapGet("/api/departments", async (AppDb db) => Results.Ok(await db.Departments.OrderBy(x=>x.Name).Select(x=>new{x.Id,x.Name,x.Description,Employees=db.Employees.Count(e=>e.DepartmentId==x.Id)}).ToListAsync())).RequireAuthorization();
app.MapPost("/api/departments", async (DepartmentInput x, ClaimsPrincipal p, AppDb db) => { var name=x.Name.Trim();if(name=="")return Results.BadRequest("Department name is required.");if(await db.Departments.AnyAsync(d=>d.Name==name))return Results.Conflict("Department already exists.");var d=new Department{Name=name,Description=x.Description?.Trim()??""};db.Departments.Add(d);await db.SaveChangesAsync();await Log(db,p,"Created department",d.Name);return Results.Ok(d); }).RequireAuthorization("AdminOnly");
app.MapPut("/api/departments/{id:int}", async(int id,DepartmentInput x,ClaimsPrincipal p,AppDb db)=>{var d=await db.Departments.FindAsync(id);if(d is null)return Results.NotFound();d.Name=x.Name.Trim();d.Description=x.Description?.Trim()??"";await db.SaveChangesAsync();await Log(db,p,"Updated department",d.Name);return Results.Ok(d);}).RequireAuthorization("AdminOnly");
app.MapDelete("/api/departments/{id:int}", async(int id,ClaimsPrincipal p,AppDb db)=>{var d=await db.Departments.FindAsync(id);if(d is null)return Results.NotFound();db.Departments.Remove(d);await db.SaveChangesAsync();await Log(db,p,"Deleted department",d.Name);return Results.NoContent();}).RequireAuthorization("AdminOnly");

// Employees
app.MapGet("/api/employees", async(AppDb db)=>Results.Ok(await db.Employees.Include(e=>e.Department).OrderBy(e=>e.Name).Select(e=>new{e.Id,e.Name,e.Email,e.Phone,e.JobTitle,e.DepartmentId,Department=e.Department!=null?e.Department.Name:"No Department",e.IsActive}).ToListAsync())).RequireAuthorization();
app.MapPost("/api/employees", async(EmployeeInput x,ClaimsPrincipal p,AppDb db)=>{if(string.IsNullOrWhiteSpace(x.Name)||string.IsNullOrWhiteSpace(x.Email))return Results.BadRequest("Name and email are required.");var e=new Employee{Name=x.Name.Trim(),Email=x.Email.Trim(),Phone=x.Phone?.Trim()??"",JobTitle=x.JobTitle?.Trim()??"",DepartmentId=x.DepartmentId,IsActive=true};db.Employees.Add(e);await db.SaveChangesAsync();await Log(db,p,"Created employee",e.Name);return Results.Ok(e);}).RequireAuthorization("AdminOnly");
app.MapPut("/api/employees/{id:int}",async(int id,EmployeeInput x,ClaimsPrincipal p,AppDb db)=>{var e=await db.Employees.FindAsync(id);if(e is null)return Results.NotFound();e.Name=x.Name.Trim();e.Email=x.Email.Trim();e.Phone=x.Phone?.Trim()??"";e.JobTitle=x.JobTitle?.Trim()??"";e.DepartmentId=x.DepartmentId;e.IsActive=x.IsActive;await db.SaveChangesAsync();await Log(db,p,"Updated employee",e.Name);return Results.Ok(e);}).RequireAuthorization("AdminOnly");
app.MapDelete("/api/employees/{id:int}",async(int id,ClaimsPrincipal p,AppDb db)=>{var e=await db.Employees.FindAsync(id);if(e is null)return Results.NotFound();db.Employees.Remove(e);await db.SaveChangesAsync();await Log(db,p,"Deleted employee",e.Name);return Results.NoContent();}).RequireAuthorization("AdminOnly");

// Tasks
app.MapGet("/api/tasks",async(ClaimsPrincipal p,AppDb db)=>{var q=db.Tasks.Include(t=>t.Assignee).Include(t=>t.Department).AsQueryable();if(!p.IsInRole("Admin")){var uid=UserId(p);q=q.Where(t=>t.AssigneeId==uid);}return Results.Ok(await q.OrderByDescending(t=>t.Id).Select(t=>new{t.Id,t.Title,t.Description,t.Status,t.Priority,t.DueDate,t.AssigneeId,Assignee=t.Assignee!=null?t.Assignee.Name:"Unassigned",t.DepartmentId,Department=t.Department!=null?t.Department.Name:"No Department"}).ToListAsync());}).RequireAuthorization();
app.MapPost("/api/tasks",async(TaskInput x,ClaimsPrincipal p,AppDb db)=>{var t=new TaskItem{Title=x.Title.Trim(),Description=x.Description?.Trim()??"",Status=NormStatus(x.Status),Priority=NormPriority(x.Priority),DueDate=x.DueDate,AssigneeId=x.AssigneeId,DepartmentId=x.DepartmentId};db.Tasks.Add(t);await db.SaveChangesAsync();await Log(db,p,"Created task",t.Title);return Results.Ok(t);}).RequireAuthorization("AdminOnly");
app.MapPut("/api/tasks/{id:int}",async(int id,TaskInput x,ClaimsPrincipal p,AppDb db)=>{var t=await db.Tasks.FindAsync(id);if(t is null)return Results.NotFound();if(!p.IsInRole("Admin")&&t.AssigneeId!=UserId(p))return Results.Forbid();t.Title=x.Title.Trim();t.Description=x.Description?.Trim()??"";t.Status=NormStatus(x.Status);t.Priority=NormPriority(x.Priority);t.DueDate=x.DueDate;t.AssigneeId=x.AssigneeId;t.DepartmentId=x.DepartmentId;await db.SaveChangesAsync();await Log(db,p,"Updated task",t.Title);return Results.Ok(t);}).RequireAuthorization();
app.MapDelete("/api/tasks/{id:int}",async(int id,ClaimsPrincipal p,AppDb db)=>{if(!p.IsInRole("Admin"))return Results.Forbid();var t=await db.Tasks.FindAsync(id);if(t is null)return Results.NotFound();db.Tasks.Remove(t);await db.SaveChangesAsync();await Log(db,p,"Deleted task",t.Title);return Results.NoContent();}).RequireAuthorization();

// Activity logs
app.MapGet("/api/logs",async(AppDb db)=>Results.Ok(await db.Logs.Include(l=>l.User).OrderByDescending(l=>l.Id).Take(100).Select(l=>new{l.Id,l.Action,l.Details,l.CreatedAt,User=l.User!=null?l.User.Name:"System"}).ToListAsync())).RequireAuthorization("AdminOnly");
app.Run();

static int UserId(ClaimsPrincipal p)=>int.Parse(p.FindFirstValue(ClaimTypes.NameIdentifier)!);
static string NormStatus(string? s)=>s is "In Progress" or "Done" ? s : "Pending";
static string NormPriority(string? s)=>s is "Low" or "High" ? s : "Medium";
static async Task Log(AppDb db, ClaimsPrincipal p,string action,string details){db.Logs.Add(new ActivityLog{UserId=UserId(p),Action=action,Details=details,CreatedAt=DateTime.UtcNow});await db.SaveChangesAsync();}
static void Seed(AppDb db){
 if(!db.Users.Any()){db.Users.AddRange(new User{Name="Administrator",Email="admin@adminpro.com",PasswordHash=Hashing.Hash("123456"),Role="Admin",IsActive=true},new User{Name="Employee",Email="employee@adminpro.com",PasswordHash=Hashing.Hash("123456"),Role="Employee",IsActive=true});db.SaveChanges();}
 if(!db.Departments.Any()){db.Departments.AddRange(new Department{Name="IT",Description="Technology and support"},new Department{Name="Human Resources",Description="People and culture"},new Department{Name="Operations",Description="Daily operations"});db.SaveChanges();}
 if(!db.Employees.Any()){var it=db.Departments.First(d=>d.Name=="IT");db.Employees.AddRange(new Employee{Name="Ahmed Hassan",Email="ahmed@adminpro.com",Phone="01000000000",JobTitle="Frontend Developer",DepartmentId=it.Id,IsActive=true},new Employee{Name="Mona Ali",Email="mona@adminpro.com",Phone="01100000000",JobTitle="HR Specialist",DepartmentId=db.Departments.First(d=>d.Name=="Human Resources").Id,IsActive=true});db.SaveChanges();}
 if(!db.Tasks.Any()){var e=db.Employees.First();db.Tasks.AddRange(new TaskItem{Title="Prepare monthly report",Description="Collect the monthly organization figures.",Status="Pending",Priority="High",DueDate=DateTime.UtcNow.Date.AddDays(5),AssigneeId=e.Id,DepartmentId=e.DepartmentId},new TaskItem{Title="Review employee accounts",Description="Review active employee records.",Status="In Progress",Priority="Medium",DueDate=DateTime.UtcNow.Date.AddDays(2),AssigneeId=e.Id,DepartmentId=e.DepartmentId},new TaskItem{Title="Update company profile",Description="Refresh organization information.",Status="Done",Priority="Low",DueDate=DateTime.UtcNow.Date.AddDays(-1),AssigneeId=e.Id,DepartmentId=e.DepartmentId});db.SaveChanges();}
}
public class AppDb:DbContext{public AppDb(DbContextOptions<AppDb> o):base(o){}public DbSet<User> Users=>Set<User>();public DbSet<Department> Departments=>Set<Department>();public DbSet<Employee> Employees=>Set<Employee>();public DbSet<TaskItem> Tasks=>Set<TaskItem>();public DbSet<ActivityLog> Logs=>Set<ActivityLog>();protected override void OnModelCreating(ModelBuilder m){m.Entity<User>().HasIndex(x=>x.Email).IsUnique();m.Entity<Employee>().HasOne(x=>x.Department).WithMany().HasForeignKey(x=>x.DepartmentId).OnDelete(DeleteBehavior.SetNull);m.Entity<TaskItem>().HasOne(x=>x.Assignee).WithMany().HasForeignKey(x=>x.AssigneeId).OnDelete(DeleteBehavior.SetNull);m.Entity<TaskItem>().HasOne(x=>x.Department).WithMany().HasForeignKey(x=>x.DepartmentId).OnDelete(DeleteBehavior.SetNull);m.Entity<ActivityLog>().HasOne(x=>x.User).WithMany().HasForeignKey(x=>x.UserId).OnDelete(DeleteBehavior.SetNull);}}
public class User{public int Id{get;set;}public string Name{get;set;}="";public string Email{get;set;}="";public string PasswordHash{get;set;}="";public string Role{get;set;}="Employee";public bool IsActive{get;set;}=true;}
public class Department{public int Id{get;set;}public string Name{get;set;}="";public string Description{get;set;}="";}
public class Employee{public int Id{get;set;}public string Name{get;set;}="";public string Email{get;set;}="";public string Phone{get;set;}="";public string JobTitle{get;set;}="";public int? DepartmentId{get;set;}public Department? Department{get;set;}public bool IsActive{get;set;}=true;}
public class TaskItem{public int Id{get;set;}public string Title{get;set;}="";public string Description{get;set;}="";public string Status{get;set;}="Pending";public string Priority{get;set;}="Medium";public DateTime? DueDate{get;set;}public int? AssigneeId{get;set;}public User? Assignee{get;set;}public int? DepartmentId{get;set;}public Department? Department{get;set;}}
public class ActivityLog{public int Id{get;set;}public string Action{get;set;}="";public string Details{get;set;}="";public DateTime CreatedAt{get;set;}public int? UserId{get;set;}public User? User{get;set;}}
public record LoginDto(string Email,string Password);public record UserInput(string Name,string Email,string Password,string Role,bool IsActive);public record DepartmentInput(string Name,string? Description);public record EmployeeInput(string Name,string Email,string? Phone,string? JobTitle,int? DepartmentId,bool IsActive);public record TaskInput(string Title,string? Description,string Status,string Priority,DateTime? DueDate,int? AssigneeId,int? DepartmentId);public record ProfileInput(string Name);public record PasswordChange(string CurrentPassword,string NewPassword);public record UserDto(int Id,string Name,string Email,string Role,bool IsActive){public static UserDto From(User u)=>new(u.Id,u.Name,u.Email,u.Role,u.IsActive);}public record UserRow(int Id,string Name,string Email,string Role,bool IsActive);
static class Hashing{public static string Hash(string v){using var s=SHA256.Create();return Convert.ToHexString(s.ComputeHash(Encoding.UTF8.GetBytes(v)));}public static bool Verify(string v,string h)=>CryptographicOperations.FixedTimeEquals(Convert.FromHexString(Hash(v)),Convert.FromHexString(h));}
